# Base image
FROM node:18.15.0-alpine

# Set the working directory in the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Expose the desired port (adjust as per your application)
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]